# Generated by Django 2.0.4 on 2020-11-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('patent', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('heartbeat', models.CharField(blank=True, max_length=200, null=True)),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Tracker - Dados',
                'verbose_name_plural': 'Tracker - Dados',
                'db_table': 'tracker_name',
            },
        ),
    ]
