# Generated by Django 2.0.4 on 2020-11-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='photo',
            field=models.ImageField(upload_to='policial'),
        ),
    ]
