# Generated by Django 2.0.4 on 2020-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201120_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='route',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='tracker',
            name='long',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
