# Generated by Django 2.0.4 on 2020-11-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201120_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='heartbeat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
